### ISSUE TITLE
shift_factors strange error

### ISSUE THREAD

**Issue by enifmada** [degleris1/cnmfpy#1]
In optimize.py, the shift_factors code has a bug that gives some odd (but not entirely bad) results.

To compute the masses used to determine the shifts, the code sums over each neuron (`masses = np.sum(W[:,k,:], axis=1)`), then shifts the components; the correct code should sum over each component (`masses = np.sum(W[:,k,:], axis=1)`).

What's strange about this bug is that it generally produces better results than unregularized CNMF: 
![bad_cnmf](https://user-images.githubusercontent.com/8041675/41244771-16e449cc-6d74-11e8-8a6b-7ffd81718af3.png)
This is the output from one run of multiplicative update CNMF with the shift_factors bug. The leftmost set of plots are the real H vectors (blue) and all of the reconstructed H vectors (yellow). The center set of plots are the real and reconstructed X matrices. The rightmost plots are the three real W matrices followed by all non-zero reconstructed W matrices.

While the reconstruction isn't great, this version of unregularized CNMF somehow correctly determines that there are three components! Across about 500 runs, this version of CNMF correctly determined the number of components ± 1 about 75% of the time. This indicates to me that summing over each neuron is somehow regularizing CNMF; this makes some amount of sense, since summing across components over each neuron allows the components to "talk" to one another.

I still can't really make sense of why this bug makes CNMF perform better than the correct implementation of CNMF in most cases (when the number of reconstructed components is capped at exactly the number of real components, this code performs MUCH worse than normal CNMF, however). Let me know if you have any insights.

Also, unrelated but still relevant to shift_factors: after shifting each component by some amount, should the 0's in the resulting W matrices have EPSILON added to them so that multiplicative update can change their values properly?

**Comment by degleris1** [comment]
Fantastic catch! I would've never noticed that myself.

Just to be clear, the correct code should be `masses = np.sum(W[:,:,k], axis=1)`. The mass at a given time lag is represented by the sum of the neurons firing at the point. The `shift_factors` function really centers the factors (perhaps we should rename this), so each archetypal sequence has the most neural activity around the center of the sequence.

What's interesting is that we still shift along the correct axis, i.e. the the function still shifts along the time lag axis (not neurons or components). This makes the bug especially hard to interpret.

Any type of shifting should act as some form of regularization; as to why it performs so much better than raw CNMF, I really don't have too much insight there. The only thing that should be "regularized" is the center of mass of each sequence, and I'm not too sure why this might also regularize the number of components.

Our code is primarily based off of [this MATLAB implementation](https://github.com/FeeLab/seqNMF), which is linked to the paper (preprint) that designed the smooth cross-factors orthogonality regularization. You may find more complete code there (this project is still a work in progress). 

You are also right that we should add `EPSILON` to the resulting matrices. Thanks for the help! If you're interested in contributing to this project in the future (we have some new features to add later this summer), please let me know!

**Comment by enifmada** [comment]
Sorry about that, my corrected code had a typo. I agree with your corrected code.

I have since moved to using CNMF in a regime where the number of patterns is less than the number of neurons, which necessitates using a L1 regularizer to enforce sparsity in H matrices instead of the seqNMF regularizer, so I haven't investigated why this bug sometimes produces good results much further.

I'm definitely interested in contributing! I have already written methods implementing calculating consistency as outlined in the paper and generating a dataset so that the underlying W matrices exist and can be compared to. Let me know if there's anything else I can do.
